# act

name: Rails

on: push

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
          # POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
      # if you need redis
      # redis:
      #   image: redis
      #   ports:
      #   - 6379:6379
      #   options: --entrypoint redis-server

    # container:
    #   image:  ruby:3.0.2
    #   env:
    #     RAILS_ENV: test
    #     # DATABASE_HOST: postgres
    #     # DATABASE_PORT: 5432
    #     # DATABASE_USER: pguser
    #     # DATABASE_PASSWORD: password
    #     # REDIS_URL: redis://redis:6379/1

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install library for postgres
        run: sudo apt-get -yqq install libpq-dev
      # - name: Install Bundler
      #   run: gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
      - name: Bundle install
        # run: bundle install --path=vendor/bundle --jobs 4 --retry 3
        # run: bundle install --jobs 4 --retry 3
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      # - name: Install Node.js
      #   run: |
      #     curl -sL https://deb.nodesource.com/setup_14.x | bash -
      #     apt-get install -y nodejs
      # - name: Install dependencies
      #   run: npm i
      - name: Setup test database
        env:
          RAILS_ENV: test
          # DATABASE_URL: postgres://pguser:password@localhost:5432/app_test
          # POSTGRES_PASSWORD: password
          DATABASE_PORT: 5432
          DATABASE_HOST: localhost
        run: |
          bundle exec rails db:create
          bundle exec rails db:seed
      - name: Run tests
        run: bundle exec rspec
